spring:
  application:
    name: second-microservice
server:
  port: 8082

  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka